"""Run OrCAD DB Tcl in a one-shot interpreter and wait for a verdict file."""
from __future__ import annotations

import os
import subprocess
import tempfile
import time
import uuid
from pathlib import Path

DEFAULT_CAPTURE_EXE = Path(r"D:\orcad\tools\bin\Capture.exe")


def _capture_exe() -> Path:
    env_path = os.environ.get("ENGIWORLD_ORCAD_CAPTURE_EXE")
    if env_path:
        return Path(env_path)
    return DEFAULT_CAPTURE_EXE


def _as_tcl_path(path: Path) -> str:
    return path.resolve().as_posix()


def _tclsh_exe(capture_exe: Path) -> Path:
    return capture_exe.with_name("tclsh.exe")


def _db_tcl_dll(capture_exe: Path) -> Path:
    bin_dir = capture_exe.parent
    candidates = [
        bin_dir / "orDb_Dll_Tcl64.dll",
        bin_dir / "orDb_Dll_Tcl.dll",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def _subprocess_env(capture_exe: Path) -> dict[str, str]:
    env = os.environ.copy()
    path_entries = env.get("PATH", "").split(os.pathsep)
    bin_dir = str(capture_exe.parent)
    if bin_dir not in path_entries:
        env["PATH"] = os.pathsep.join([bin_dir, *[entry for entry in path_entries if entry]])
    env.setdefault("CDS_INST_DIR", str(capture_exe.parents[2]))
    return env


def _build_job_script(job_id: str, tcl_body: str, dll_path: Path, err_path: Path) -> str:
    dll_tcl = _as_tcl_path(dll_path)
    err_tcl = _as_tcl_path(err_path)
    return f"""# auto-generated by run_in_capture.py
namespace eval ::engiworld {{
    variable created_session 0
    proc write_text {{path text}} {{
        set fd [open $path w]
        puts -nonewline $fd $text
        close $fd
    }}
    proc ensure_session {{}} {{
        variable created_session
        if {{![catch {{package require DboTclWriteBasic}}]}} {{
            # already available
        }} else {{
            load "{dll_tcl}" DboTclWriteBasic
            package require DboTclWriteBasic
        }}
        if {{![info exists ::DboSession_s_pDboSession] || $::DboSession_s_pDboSession eq "" || $::DboSession_s_pDboSession eq "NULL"}} {{
            set ::DboSession_s_pDboSession [DboTclHelper_sCreateSession]
            DboSession -this $::DboSession_s_pDboSession
            set created_session 1
        }}
    }}
    proc cleanup {{}} {{
        variable created_session
        catch {{DboTclHelper_sReleaseAllCreatedPtrs}}
        if {{$created_session && [info exists ::DboSession_s_pDboSession] && $::DboSession_s_pDboSession ne "NULL"}} {{
            catch {{DboTclHelper_sDeleteSession $::DboSession_s_pDboSession}}
            catch {{unset ::DboSession_s_pDboSession}}
        }}
    }}
    proc run_job {{}} {{
        if {{[catch {{
            ensure_session
namespace eval ::job_{job_id} {{
{tcl_body}
}}
        }} err opts]}} {{
            set details $err
            if {{[info exists ::errorInfo]}} {{
                append details "\\n" $::errorInfo
            }}
            write_text "{err_tcl}" $details
        }}
        cleanup
    }}
}}
::engiworld::run_job
exit
"""


def run_in_capture(
    tcl_body: str,
    out_path: Path,
    timeout_s: int = 120,
    poll_interval: float = 1.0,
    verbose: bool = True,
) -> bool:
    """Run `tcl_body` in a fresh one-shot OrCAD Tcl session and wait for `out_path`."""
    capture_exe = _capture_exe()
    if not capture_exe.exists():
        if verbose:
            print(f"[run_in_capture] Capture executable not found: {capture_exe}")
        return False
    tclsh_exe = _tclsh_exe(capture_exe)
    if not tclsh_exe.exists():
        if verbose:
            print(f"[run_in_capture] Tcl shell not found next to Capture.exe: {tclsh_exe}")
        return False
    db_tcl_dll = _db_tcl_dll(capture_exe)
    if not db_tcl_dll.exists():
        if verbose:
            print(f"[run_in_capture] OrCAD DB Tcl DLL not found: {db_tcl_dll}")
        return False

    if out_path.exists():
        try:
            out_path.unlink()
        except PermissionError:
            pass

    job_id = uuid.uuid4().hex[:8]
    with tempfile.TemporaryDirectory(prefix="engiworld_capture_eval_") as tmpdir:
        tmp = Path(tmpdir)
        job_path = tmp / f"job_{job_id}.tcl"
        err_path = tmp / f"job_{job_id}.err"
        job_path.write_text(_build_job_script(job_id, tcl_body, db_tcl_dll, err_path), encoding="utf-8")

        if verbose:
            print(f"[run_in_capture] launching {tclsh_exe}")
            print(f"[run_in_capture] script: {job_path}")
            print(f"[run_in_capture] waiting for {out_path}")

        proc = None
        try:
            proc = subprocess.Popen(
                [str(tclsh_exe), str(job_path)],
                cwd=str(capture_exe.parent),
                env=_subprocess_env(capture_exe),
            )
            deadline = time.time() + timeout_s
            while time.time() < deadline:
                if out_path.exists() and out_path.stat().st_size > 0:
                    return True
                if err_path.exists():
                    if verbose:
                        print("[run_in_capture] ERROR from Capture:")
                        print(err_path.read_text(encoding="utf-8", errors="replace"))
                    return False
                if proc.poll() is not None and not out_path.exists() and not err_path.exists():
                    if verbose:
                        print(f"[run_in_capture] Tcl runner exited with code {proc.returncode}")
                    return False
                time.sleep(poll_interval)
            if verbose:
                print(f"[run_in_capture] timed out after {timeout_s}s; verdict not produced")
            return False
        finally:
            if proc is not None and proc.poll() is None:
                try:
                    proc.terminate()
                    proc.wait(timeout=10)
                except Exception:
                    try:
                        proc.kill()
                    except Exception:
                        pass


def read_verdict(out_path: Path) -> dict | None:
    import json
    if not out_path.exists():
        return None
    try:
        return json.loads(out_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[run_in_capture] could not parse verdict json: {e}")
        return None
