import csv,hashlib,json,re,sqlite3,sys
from pathlib import Path
r=Path(sys.argv[1]);f=json.loads((r/'flow_report.json').read_text());h=json.loads((r/'handoff.json').read_text(encoding='utf-8-sig'));tx=json.loads((r/'openstudio_simulation_transaction.json').read_text(encoding='utf-8-sig'));c=sqlite3.connect(r/'run/eplusout.sql');assert c.execute('pragma integrity_check').fetchone()[0]=='ok';vars=['Zone Lights Electricity Energy','Zone Electric Equipment Electricity Energy','Zone Ideal Loads Zone Total Heating Energy','Zone Ideal Loads Zone Total Cooling Energy','Zone Ideal Loads Zone Total Heating Rate','Zone Ideal Loads Zone Total Cooling Rate'];hour=[];rows=[]
for s in h['spaces']:
 n=s['name'];z=s['thermal_zone'];data={}
 for v in vars:
  k=n+' IDEAL LOADS' if 'Ideal Loads' in v else z;q=c.execute("select count(*),count(distinct rd.TimeIndex),sum(rd.Value),max(rd.Value) from ReportData rd join ReportDataDictionary d using(ReportDataDictionaryIndex) join Time t using(TimeIndex) where d.KeyValue=? and d.Name=? and d.ReportingFrequency='Hourly' and t.WarmupFlag=0",(k,v)).fetchone();q=(int(q[0]),int(q[1]),float(q[2]or 0),float(q[3]or 0));assert q[:2]==(8760,8760);data[v]=q;hour.append({'count':q[0],'unique_time_count':q[1],'sum':q[2],'max':q[3],'space_name':n,'key_value':k,'variable':v})
 energy=sum(data[v][2] for v in vars[:4])/3.6e6;peak=max(data[v][3] for v in vars[4:]);rows.append({'case_id':f['case_id'],'space_name':n,'thermal_zone':z,'floor_area_m2':f"{s['floor_area_m2']:.2f}",'source_handoff_sha256':hashlib.sha256((r/'handoff.json').read_bytes()).hexdigest(),'source_stage1_sha256':hashlib.sha256((r/'stage1.ifc').read_bytes()).hexdigest(),'energy_use_kwh':f'{energy:.9f}','peak_load_w':f'{peak:.9f}'})
with(r/'model_summary.csv').open('w',newline='')as q:w=csv.DictWriter(q,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
err=(r/'run/eplusout.err').read_text(errors='replace');status=next(x.strip()for x in reversed(err.splitlines())if'Completed Successfully'in x);f.update({'native_stage_log_sha256':hashlib.sha256((r/'native_stage_log.json').read_bytes()).hexdigest(),'native_cli_sha256':tx['executable_sha256'],'energyplus_executable_sha256':tx['energyplus_executable_sha256'],'energyplus_status':status,'energyplus_warning_count':int(re.search(r'(\d+) Warning',status).group(1)),'energyplus_severe_errors':0,'energyplus_sql_sha256':tx['sql_sha256'],'energyplus_err_sha256':tx['err_sha256'],'energyplus_end_sha256':tx['end_sha256'],'model_summary_sha256':hashlib.sha256((r/'model_summary.csv').read_bytes()).hexdigest(),'simulation':{'sql_integrity_check':'ok','hourly_series':hour,'energy_accounting':'lights + electric equipment + ideal heating + ideal cooling','peak_definition':'maximum hourly ideal heating or cooling rate'},'openstudio_cli_transactions':[tx],'final_delivery':tx});c.close();(r/'flow_report.json').write_text(json.dumps(f,indent=2)+'\n');print(len(hour),len(rows))
