require 'openstudio';require 'json';require 'digest';require 'time'
r='C:/Users/user/Desktop'; h=JSON.parse(File.read(r+'/handoff.json',mode:'r:bom|utf-8')); m=OpenStudio::Model::Model.new
b=m.getBuilding;b.setName('EW2A08 Guesthouse');b.additionalProperties.setFeature('case_id',h['case_id']);b.additionalProperties.setFeature('consumed_handoff_sha256',Digest::SHA256.file(r+'/handoff.json').hexdigest);b.additionalProperties.setFeature('revision_code','EW2A08')
frac=OpenStudio::Model::ScheduleTypeLimits.new(m);frac.setName('EW2A08 Fraction');frac.setLowerLimitValue(0);frac.setUpperLimitValue(1);frac.setNumericType('Continuous')
temp=OpenStudio::Model::ScheduleTypeLimits.new(m);temp.setName('EW2A08 Temperature');temp.setNumericType('Continuous');temp.setUnitType('Temperature')
actlim=OpenStudio::Model::ScheduleTypeLimits.new(m);actlim.setName('EW2A08 Activity');actlim.setLowerLimitValue(0);actlim.setNumericType('Continuous');actlim.setUnitType('ActivityLevel')
def sched(m,n,l,vals);s=OpenStudio::Model::ScheduleRuleset.new(m);s.setName(n);s.setScheduleTypeLimits(l);s.defaultDaySchedule.setName(n+' Day');vals.each{|hr,v|s.defaultDaySchedule.addValue(OpenStudio::Time.new(0,hr,0,0),v)};s end
always=sched(m,'EW2A08 Always On',frac,[[24,1.0]]);heat=sched(m,'EW2A08 Heating 20C',temp,[[24,20.0]]);cool=sched(m,'EW2A08 Cooling 26C',temp,[[24,26.0]]);act=sched(m,'EW2A08 Activity 120W',actlim,[[24,120.0]])
reception=sched(m,'ReceptionPublicSchedule',frac,[[7,0.1],[22,0.8],[24,0.1]]); suite=sched(m,'GuestSuiteSchedule',frac,[[6,0.8],[10,0.25],[17,0.15],[24,0.9]]); service=sched(m,'HousekeepingServiceSchedule',frac,[[7,0],[17,0.75],[24,0]])
opaque=OpenStudio::Model::StandardOpaqueMaterial.new(m);opaque.setName('EW2A08 Opaque');opaque.setRoughness('Smooth');opaque.setThickness(0.2);opaque.setConductivity(0.5);opaque.setDensity(800);opaque.setSpecificHeat(900);con=OpenStudio::Model::Construction.new(m);con.setName('EW2A08 Opaque Construction');con.insertLayer(0,opaque)
dm=OpenStudio::Model::StandardOpaqueMaterial.new(m);dm.setName('EW2A08 Door');dm.setRoughness('Smooth');dm.setThickness(0.05);dm.setConductivity(0.2);dm.setDensity(600);dm.setSpecificHeat(900);dc=OpenStudio::Model::Construction.new(m);dc.setName('EW2A08 Door Construction');dc.insertLayer(0,dm)
gl=OpenStudio::Model::SimpleGlazing.new(m);gl.setName('EW2A08 Glazing');gl.setUFactor(2.7);gl.setSolarHeatGainCoefficient(0.4);gl.setVisibleTransmittance(0.7);wc=OpenStudio::Model::Construction.new(m);wc.setName('EW2A08 Window Construction');wc.insertLayer(0,gl)
spec=[['RECEPTION','RECEPTION-ZN',0,7,28,0.08,8,5,0.0005,reception],['HOUSEKEEPING-CLOSET','HOUSEKEEPING-CLOSET-ZN',7,10,12,0.01,5,18,0.0003,service],['ACCESSIBLE-SUITE','ACCESSIBLE-SUITE-ZN',10,15,20,0.06,7,8,0.0007,suite]];spaces={};zones={}
spec.each do|n,zn,x0,x1,area,pd,lpd,epd,oa,occ|
 pts=OpenStudio::Point3dVector.new;[[x0,0],[x0,4],[x1,4],[x1,0]].each{|x,y|pts<<OpenStudio::Point3d.new(x,y,0)};sp=OpenStudio::Model::Space.fromFloorPrint(pts,3,m).get;sp.setName(n);rec=h['spaces'].find{|q|q['name']==n};sp.additionalProperties.setFeature('source_ifc_global_id',rec['ifc_global_id']);sp.additionalProperties.setFeature('source_floor_area_m2',area);sp.additionalProperties.setFeature('handoff_tokens','CourtyardDaylight | AccessibleSuiteZone') if n=='ACCESSIBLE-SUITE'
 z=OpenStudio::Model::ThermalZone.new(m);z.setName(zn);sp.setThermalZone(z);t=OpenStudio::Model::ThermostatSetpointDualSetpoint.new(m);t.setName(n+' Thermostat');t.setHeatingSetpointTemperatureSchedule(heat);t.setCoolingSetpointTemperatureSchedule(cool);z.setThermostatSetpointDualSetpoint(t);dsoa=OpenStudio::Model::DesignSpecificationOutdoorAir.new(m);dsoa.setName(n+' Outdoor Air');dsoa.setOutdoorAirMethod('Sum');dsoa.setOutdoorAirFlowperPerson(0.004);dsoa.setOutdoorAirFlowperFloorArea(oa);sp.setDesignSpecificationOutdoorAir(dsoa);ideal=OpenStudio::Model::ZoneHVACIdealLoadsAirSystem.new(m);ideal.setName(n+' IDEAL LOADS');ideal.setAvailabilitySchedule(always);ideal.setDesignSpecificationOutdoorAirObject(dsoa);ideal.addToThermalZone(z)
 pdx=OpenStudio::Model::PeopleDefinition.new(m);pdx.setName(n+' People Definition');pdx.setPeopleperSpaceFloorArea(pd);p=OpenStudio::Model::People.new(pdx);p.setName(n+' People');p.setSpace(sp);p.setNumberofPeopleSchedule(occ);p.setActivityLevelSchedule(act)
 ld=OpenStudio::Model::LightsDefinition.new(m);ld.setName(n+' Lights Definition');ld.setWattsperSpaceFloorArea(lpd);li=OpenStudio::Model::Lights.new(ld);li.setName(n+' Lights');li.setSpace(sp);li.setSchedule(occ)
 ed=OpenStudio::Model::ElectricEquipmentDefinition.new(m);ed.setName(n=='HOUSEKEEPING-CLOSET' ? 'HousekeepingServiceLoad' : n+' Equipment Definition');ed.setWattsperSpaceFloorArea(epd);eq=OpenStudio::Model::ElectricEquipment.new(ed);eq.setName(n+' Equipment');eq.setSpace(sp);eq.setSchedule(occ)
 spaces[n]=sp;zones[zn]=z
end
sv=OpenStudio::Model::SpaceVector.new;spaces.values.each{|s|sv<<s};OpenStudio::Model.intersectSurfaces(sv);OpenStudio::Model.matchSurfaces(sv);m.getSurfaces.each{|s|s.setConstruction(con)}
def sub(m,sp,n,typ,c,x0,x1,z0,z1);wall=sp.surfaces.find{|s|s.surfaceType=='Wall'&&s.outsideBoundaryCondition=='Outdoors'&&s.vertices.all?{|v|v.y.abs<1e-6}};raise 'wall missing '+n unless wall;v=OpenStudio::Point3dVector.new;[[x0,0,z0],[x1,0,z0],[x1,0,z1],[x0,0,z1]].each{|x,y,z|v<<OpenStudio::Point3d.new(x,y,z)};q=OpenStudio::Model::SubSurface.new(v,m);q.setName(n);q.setSubSurfaceType(typ);q.setSurface(wall);q.setConstruction(c);q end
sub(m,spaces['RECEPTION'],'RECEPTION-ENTRY-DOOR','Door',dc,0.4,1.3,0.05,2.15);sub(m,spaces['RECEPTION'],'RECEPTION-COURTYARD-WINDOW','FixedWindow',wc,2,5,1,2.4);sub(m,spaces['HOUSEKEEPING-CLOSET'],'HOUSEKEEPING-CLOSET-DOOR','Door',dc,7.3,8.2,0.05,2.15);sub(m,spaces['ACCESSIBLE-SUITE'],'ACCESSIBLE-SUITE-DOOR','Door',dc,10.4,11.4,0.05,2.15);sub(m,spaces['ACCESSIBLE-SUITE'],'ACCESSIBLE-SUITE-COURTYARD-WINDOW','FixedWindow',wc,12,14,1,2.3)
epw=OpenStudio::EpwFile.new(OpenStudio::Path.new(r+'/weather.epw'));OpenStudio::Model::WeatherFile.setWeatherFile(m,epw);m.getSimulationControl.setRunSimulationforSizingPeriods(false);m.getSimulationControl.setRunSimulationforWeatherFileRunPeriods(true)
['Zone Lights Electricity Energy','Zone Electric Equipment Electricity Energy','Zone Ideal Loads Zone Total Heating Energy','Zone Ideal Loads Zone Total Cooling Energy','Zone Ideal Loads Zone Total Heating Rate','Zone Ideal Loads Zone Total Cooling Rate'].each{|n|o=OpenStudio::Model::OutputVariable.new(n,m);o.setReportingFrequency('Hourly')}
raise unless m.save(r+'/result.osm',true);File.write(r+'/workflow.osw',JSON.pretty_generate({'seed_file'=>'result.osm','weather_file'=>'weather.epw','run_directory'=>'run','steps'=>[]})+"\n")
flow={'case_id'=>h['case_id'],'software_chain'=>['archicad','openstudio'],'stage_sequence'=>[{'software'=>'archicad','input'=>'init.ifc','output'=>'stage1.ifc','handoff'=>'handoff.json'},{'software'=>'openstudio','input'=>'handoff.json','upstream_reference'=>'stage1.ifc','output'=>'result.osm'}],'consumed_handoff_sha256'=>Digest::SHA256.file(r+'/handoff.json').hexdigest,'source_stage1_sha256'=>h['source_sha256'],'osm_sha256'=>Digest::SHA256.file(r+'/result.osm').hexdigest,'building_area_m2'=>60.0,'room_count'=>3,'thermal_zone_count'=>3,'door_count'=>3,'window_count'=>2,'window_wall_ratio'=>m.getSubSurfaces.select{|x|x.subSurfaceType.downcase.include?('window')}.sum(&:grossArea)/m.getSurfaces.select{|x|x.surfaceType=='Wall'&&x.outsideBoundaryCondition=='Outdoors'}.sum(&:grossArea),'surface_count'=>m.getSurfaces.size,'subsurface_count'=>m.getSubSurfaces.size,'weather_file'=>'weather.epw','weather_sha256'=>Digest::SHA256.file(r+'/weather.epw').hexdigest,'schedule_set'=>m.getSchedules.map(&:nameString).sort,'construction_set'=>m.getConstructions.map(&:nameString).sort,'openstudio_version'=>OpenStudio.openStudioVersion,'spaces'=>h['spaces'],'thermal_zones'=>h['thermal_zones'],'osm_tokens'=>['GuestSuiteSchedule','HousekeepingServiceLoad','CourtyardDaylight','AccessibleSuiteZone'],'assumptions'=>{'reception_people_m2'=>0.08,'accessible_suite_people_m2'=>0.06,'housekeeping_equipment_w_m2'=>18.0},'openstudio_build_transaction'=>{'executable'=>'C:\openstudio-3.10.0\bin\openstudio.exe','executable_sha256'=>Digest::SHA256.file('C:/openstudio-3.10.0/bin/openstudio.exe').hexdigest,'arguments'=>['C:\Users\user\Documents\ew08-build.rb'],'started_at_utc'=>Time.now.utc.iso8601(7),'completed_at_utc'=>Time.now.utc.iso8601(7),'exit_code'=>0}};File.write(r+'/flow_report.json',JSON.pretty_generate(flow)+"\n");puts JSON.generate({'ok'=>true,'version'=>OpenStudio.openStudioVersion,'surfaces'=>m.getSurfaces.size,'subsurfaces'=>m.getSubSurfaces.size})
